globalProperties:
  apiTests: true
  modelTests: true
  gitUserId: getlago
  gitRepoId: lago-python

additionalProperties:
  packageName: lago_python
  packageUrl: https://github.com/getlago/lago-python
  packageVersion: API_VERSION
  projectName: lago_python
